apiVersion: v1
kind: Service
metadata:
  name: testserver:latest1

spec:
  type: NodePort
  selector:
    app: testserver:latest1

  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000